### ISSUE TITLE
Please cherry-pick valgrind $ORIGIN patch from upstream

### ISSUE THREAD

**Issue by geofft** [CodSpeedHQ/valgrind-codspeed#1]
Hi! Valgrind upstream just recently fixed [bug 396415 "Valgrind is not looking up $ORIGIN rpath of shebang programs"](https://bugs.kde.org/show_bug.cgi?id=396415) with [commit 1fefba79021779d840bbf8cebc43e40c74b40f31](https://sourceware.org/git/?p=valgrind.git;a=commitdiff;h=1fefba79021779d840bbf8cebc43e40c74b40f31). This bug causes the Python installations used by `uv` to not work properly under CodSpeed. Specifically, if you run something like `codspeed run pytest`, `pytest` is a script whose shebang line references the Python installation, and valgrind does not run the Python interpreter properly.

Valgrind seems to release once or twice a year at most; can you please cherry-pick this patch onto your fork and include it in a CodSpeed release so `uv` users can get unblocked before then?

A simple reproducer is to do something like `uv venv; . .venv/bin/activate; uv pip install pytest; codspeed run pytest`, or something like this in GitHub Actions (see [this sample run](https://github.com/geofft/actions-test-202112/actions/runs/13039184914/job/36376851113)):

```yaml
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: astral-sh/setup-uv@v5
with:
python-version: 3.13
- run: uv pip install pytest
- uses: CodSpeedHQ/action@v3
with:
run: pytest
```

**Comment by art049** [comment]
Hello, thanks for mentioning this. Will do a release ASAP and use it with the runner.

**Comment by art049** [comment]
Done. Will release this with the next runner release. Thanks for notifying us about this.

**Comment by geofft** [comment]
Hi, just checking in case I'm missing something—this was in runner 3.4.0, right? I'm still seeing the failure here:
https://github.com/geofft/actions-test-202112/actions/runs/13554709488/job/37886346486
https://github.com/geofft/actions-test-202112/actions/runs/13554709488/workflow
Is there a way to confirm the patched valgrind is in use?

**Comment by art049** [comment]
Hi, yes the new valgrind version is in use starting from 3.4.0. 

We got uv working with Github Action on this version, and added [an example in our docs](https://docs.codspeed.io/benchmarks/python#usage-with-uv).

The only difference I see is you used `setup-uv` to install python as well while we used `setup-python`. I know there might be some differences since the builds are not the same.

Please let me know if that fixes the issue so I can add it to our documentation 🙂

**Comment by nathanjmcdougall** [comment]
For what it's worth, I'm [also getting this failure](https://github.com/nathanjmcdougall/usethis-python/actions/runs/13744580092/job/38437951960?pr=334) on v3.4.0.

From my perspective, the primary motivation for this change is to enable the use of `setup-uv` _instead of_ `setup-python`, to simplify config.
